### ISSUE TITLE
cannot build project on MacOS

### ISSUE THREAD

**Issue by pzoltowski** [meshula/LabSoundGraphToy#3]
I tried to tinker with this repo but couldn't build project. Got the following error:
```

pz@ build % cmake -G Xcode ..
-- The C compiler identification is AppleClang 12.0.0.12000032
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for stdbool.h
-- Looking for stdbool.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Checking processor clipping capabilities...
-- Performing Test CPU_CLIPS_POSITIVE
-- Performing Test CPU_CLIPS_POSITIVE - Failed
-- Performing Test CPU_CLIPS_NEGATIVE
-- Performing Test CPU_CLIPS_NEGATIVE - Failed
-- Checking processor clipping capabilities... none
-- Performing Test HAVE_VISIBILITY
-- Performing Test HAVE_VISIBILITY - Success
-- Using RtAudio backend
CMake Error at CMakeLists.txt:247 (target_link_libraries):
  Cannot specify link libraries for target "usd_ms" which is not built by
  this project.


-- Configuring incomplete, errors occurred!
See also "/Users/patryk/Developer/compile/LabSoundGraphToy/build/CMakeFiles/CMakeOutput.log".
See also "/Users/patryk/Developer/compile/LabSoundGraphToy/build/CMakeFiles/CMakeError.log".
```

**Comment by meshula** [comment]
My mistake, that was a bad merge on my part. Try pulling now.

**Comment by pzoltowski** [comment]
Thanks, It helped to create makefile however when compiling it throws some errors related to **tinyosc** library:

```
In file included from /Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.cpp:7:
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc-net.hpp:33:13: error: function definition does not declare parameters
    int32_t the_error {0};
            ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc-net.hpp:35:17: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
    osc_url() = default;
                ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc-net.hpp:37:39: error: use of undeclared identifier 'the_error'
    bool check_error() const { return the_error == 0; }
                                      ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc-net.hpp:40:9: error: use of undeclared identifier 'the_error'
        the_error = 0;
        ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc-net.hpp:56:17: error: use of undeclared identifier 'the_error'
                the_error = 1;
                ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc-net.hpp:64:13: error: use of undeclared identifier 'the_error'
            the_error = 2;





/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:71:18: error: function definition does not declare parameters
        uint64_t v{1};  // the highest 32-bit are seconds, the lowest are fraction of a second.
                 ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:73:22: warning: defaulted function definitions are a C++11 extension [-Wc++11-extensions]
        time_tag() = default;
                     ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:74:41: error: member initializer 'v' does not name a non-static data member or base class
        explicit time_tag(uint64_t w) : v(w) {}
                                        ^~~~
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:75:44: error: use of undeclared identifier 'v'
        operator uint64_t() const { return v; }
                                           ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:300:45: error: a space is required between consecutive right angle brackets (use '> >')
        std::vector<std::pair<size_t, size_t>> arguments;  // array of pairs (pos,size), pos being an index into the 'storage' array.
                                            ^~
                                            > >



/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:616:22: error: expression is not an integral constant expression
                case osc_type_tag::TYPE_TAG_TRUE:
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:617:22: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                case osc_type_tag::TYPE_TAG_FALSE: sz = 0; break;
                     ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:617:22: error: expression is not an integral constant expression
                case osc_type_tag::TYPE_TAG_FALSE: sz = 0; break;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:618:22: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                case osc_type_tag::TYPE_TAG_INT32:
                     ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:618:22: error: expression is not an integral constant expression
                case osc_type_tag::TYPE_TAG_INT32:
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:619:22: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                case osc_type_tag::TYPE_TAG_FLOAT: sz = 4; break;
                     ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:619:22: error: expression is not an integral constant expression
                case osc_type_tag::TYPE_TAG_FLOAT: sz = 4; break;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:620:22: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                case osc_type_tag::TYPE_TAG_INT64:
                     ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:620:22: error: expression is not an integral constant expression
                case osc_type_tag::TYPE_TAG_INT64:
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:621:22: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                case osc_type_tag::TYPE_TAG_DOUBLE: sz = 8; break;
                     ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:621:22: error: expression is not an integral constant expression
                case osc_type_tag::TYPE_TAG_DOUBLE: sz = 8; break;
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:622:22: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                case osc_type_tag::TYPE_TAG_STRING:
                     ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:622:22: error: expression is not an integral constant expression
                case osc_type_tag::TYPE_TAG_STRING:
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:635:22: warning: use of enumeration in a nested name specifier is a C++11 extension [-Wc++11-extensions]
                case osc_type_tag::TYPE_TAG_BLOB:
                     ^
/Users/patryk/Developer/compile/LabSoundGraphToy/third/tinyosc/tinyosc.hpp:635:22: error: expression is not an integral constant expression
                case osc_type_tag::TYPE_TAG_BLOB:
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by pzoltowski** [comment]
when compiling isolated standalone **tinyosc** repo, it compiled without problems though:

patryk@pzothink build % cmake ..
-- The CXX compiler identification is AppleClang 12.0.0.12000032
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/patryk/Developer/compile/tinyosc/build

**Comment by pzoltowski** [comment]
I confirm that when pulled **tinyosc** from **master** it fixed those above issues. It stalled at the following errors:

```
/Users/patryk/Developer/compile/LabSoundGraphToy/third/LabMidi/src/LabMidiSong.cpp:446:70: error: no member named 'pow' in namespace 'std'; did you mean simply 'pow'?
                event->timeSignature = double(*dataStart++) / double(std::pow(2, *dataStart++));
                                                                     ^~~~~~~~
                                                                     pow
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/math.h:1039:1: note: 'pow' declared here
pow(_A1 __lcpp_x, _A2 __lcpp_y) _NOEXCEPT



[ 49%] Building CXX object third/LabMidi/CMakeFiles/LabMidiPlayerApp.dir/examples/MidiPlayerApp.cpp.o
/Users/patryk/Developer/compile/LabSoundGraphToy/src/main.cpp:32:6: error: no template named 'unordered_map' in namespace 'std'
std::unordered_map<std::string, int> _addr_map;
~~~~~^
/Users/patryk/Developer/compile/LabSoundGraphToy/src/main.cpp:33:6: error: no template named 'unordered_map' in namespace 'std'
std::unordered_map<int, int> _id_argc_map;
~~~~~^
2 errors generated.

```

including the following in corresponding files resolved those errors and moved forward. 
#include <cmath>
#include <unordered_map>


Last batch of errors is unclear thought:

```
In file included from /Users/patryk/Developer/compile/LabSoundGraphToy/src/LabSoundInterface.h:9:
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.h:72:29: error: implicit instantiation of undefined template 'std::__1::vector<ln_Pin, std::__1::allocator<ln_Pin> >'
        std::vector<ln_Pin> pins;
                            ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iosfwd:216:28: note: template is declared here
class _LIBCPP_TEMPLATE_VIS vector;
                           ^
[ 98%] Building CXX object CMakeFiles/LabSoundGraphToy.dir/src/OSCNode.cpp.o
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2011:46: warning: format specifies type 'int' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
            ImGui::Text("group hovered: %d", hover.group_id.id);
                                        ~~   ^~~~~~~~~~~~~~~~~
                                        %llu
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2012:51: warning: format specifies type 'int' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
            ImGui::Text("originating pin id: %d", hover.originating_pin_id.id);
                                             ~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                             %llu
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2013:47: warning: format specifies type 'int' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
            ImGui::Text("hovered pin id: %d", hover.pin_id.id);
                                         ~~   ^~~~~~~~~~~~~~~
                                         %llu
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2014:50: warning: format specifies type 'int' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
            ImGui::Text("hovered pin label: %d", hover.pin_label_id.id);
                                            ~~   ^~~~~~~~~~~~~~~~~~~~~
                                            %llu
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2015:51: warning: format specifies type 'int' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
            ImGui::Text("hovered connection: %d", hover.connection_id.id);
                                             ~~   ^~~~~~~~~~~~~~~~~~~~~~
                                             %llu
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2017:52: warning: format specifies type 'int' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
            ImGui::Text("hovered size widget: %d", hover.size_widget_node_id.id);
                                              ~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                              %llu
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2021:48: warning: format specifies type 'int' but the argument has type 'uint64_t' (aka 'unsigned long long') [-Wformat]
            ImGui::Text("edit connection: %d", edit.selected_connection.id);
                                          ~~   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                          %llu
In file included from /Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2:
In file included from /Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:479:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:2143:45: error: static_cast from 'std::__1::unique_ptr<std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *>,
      std::__1::__tree_node_destructor<std::__1::allocator<std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> > > >::pointer' (aka 'std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *') to
      'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node,
      lab::noodle::NoodleNode> > >::__node_base_pointer' (aka 'std::__1::__tree_node_base<void *> *'), which are not related by inheritance, is not allowed
        __insert_node_at(__parent, __child, static_cast<__node_base_pointer>(__h.get()));
                                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:1519:20: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::__emplace_unique_key_args<ln_Node, const
      std::__1::piecewise_construct_t &, std::__1::tuple<const ln_Node &>, std::__1::tuple<> >' requested here
    return __tree_.__emplace_unique_key_args(__k,
                   ^
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:346:42: note: in instantiation of member function 'std::__1::map<ln_Node, lab::noodle::NoodleNode, cmp_ln_Node, std::__1::allocator<std::__1::pair<const ln_Node, lab::noodle::NoodleNode> >
      >::operator[]' requested here
                    provider._noodleNodes[edit._device_node] = NoodleNode("Device", conformed_name, edit._device_node);
                                         ^
In file included from /Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2:
In file included from /Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:479:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:874:62: error: cannot initialize a member subobject of type 'std::__1::__tree_iterator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *, long>::__iter_pointer' (aka 'std::__1::__tree_end_node<std::__1::__tree_node_base<void *> *> *') with an lvalue of type
      'std::__1::__tree_iterator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *, long>::__node_pointer' (aka
      'std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *')
    explicit __tree_iterator(__node_pointer __p) _NOEXCEPT : __ptr_(__p) {}
                                                             ^      ~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:2147:33: note: in instantiation of member function 'std::__1::__tree_iterator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *, long>::__tree_iterator' requested here
    return pair<iterator, bool>(iterator(__r), __inserted);
                                ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:1519:20: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::__emplace_unique_key_args<ln_Node, const
      std::__1::piecewise_construct_t &, std::__1::tuple<const ln_Node &>, std::__1::tuple<> >' requested here
    return __tree_.__emplace_unique_key_args(__k,
                   ^
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:346:42: note: in instantiation of member function 'std::__1::map<ln_Node, lab::noodle::NoodleNode, cmp_ln_Node, std::__1::allocator<std::__1::pair<const ln_Node, lab::noodle::NoodleNode> >
      >::operator[]' requested here
                    provider._noodleNodes[edit._device_node] = NoodleNode("Device", conformed_name, edit._device_node);
                                         ^
In file included from /Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:2:
In file included from /Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.h:8:
In file included from /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:479:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:2346:14: error: no matching constructor for initialization of 'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::iterator' (aka
      '__tree_iterator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *, long>')
    iterator __r(__ptr);
             ^   ~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:2520:20: note: in instantiation of member function 'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::__remove_node_pointer' requested here
    iterator __r = __remove_node_pointer(__np);
                   ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/map:1301:56: note: in instantiation of member function 'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::erase' requested here
    iterator erase(iterator __p)       {return __tree_.erase(__p.__i_);}
                                                       ^
/Users/patryk/Developer/compile/LabSoundGraphToy/src/lab_noodle.cpp:607:43: note: in instantiation of member function 'std::__1::map<ln_Node, lab::noodle::NoodleNode, cmp_ln_Node, std::__1::allocator<std::__1::pair<const ln_Node, lab::noodle::NoodleNode> >
      >::erase' requested here
                    provider._noodleNodes.erase(n_it);
                                          ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:816:28: note: candidate constructor (the implicit copy constructor) not viable: no known conversion from
      'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node,
      lab::noodle::NoodleNode> > >::__node_pointer' (aka 'std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *') to 'const std::__1::__tree_iterator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *, long>' for 1st argument
class _LIBCPP_TEMPLATE_VIS __tree_iterator
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:816:28: note: candidate constructor (the implicit move constructor) not viable: no known conversion from
      'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node,
      lab::noodle::NoodleNode> > >::__node_pointer' (aka 'std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *') to 'std::__1::__tree_iterator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *, long>' for 1st argument
class _LIBCPP_TEMPLATE_VIS __tree_iterator
                           ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:876:14: note: candidate constructor not viable: no known conversion from 'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::__node_pointer' (aka
      'std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *') to 'std::__1::__tree_iterator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, std::__1::__tree_node<std::__1::__value_type<ln_Node,
      lab::noodle::NoodleNode>, void *> *, long>::__end_node_pointer' (aka 'std::__1::__tree_end_node<std::__1::__tree_node_base<void *> *> *') for 1st argument
    explicit __tree_iterator(__end_node_pointer __p) _NOEXCEPT : __ptr_(__p) {}
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:834:31: note: candidate constructor not viable: requires 0 arguments, but 1 was provided
    _LIBCPP_INLINE_VISIBILITY __tree_iterator() _NOEXCEPT
                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:2348:24: error: comparison of distinct pointer types ('std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::__iter_pointer'
      (aka 'std::__1::__tree_end_node<std::__1::__tree_node_base<void *> *> *') and 'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>,
      cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::__node_pointer' (aka 'std::__1::__tree_node<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, void *> *'))
    if (__begin_node() == __ptr)
        ~~~~~~~~~~~~~~ ^  ~~~~~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/__tree:2352:19: error: static_cast from 'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, std::__1::__map_value_compare<ln_Node,
      std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>, std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::__node_pointer' (aka 'std::__1::__tree_node<std::__1::__value_type<ln_Node,
      lab::noodle::NoodleNode>, void *> *') to 'std::__1::__tree<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, std::__1::__map_value_compare<ln_Node, std::__1::__value_type<ln_Node, lab::noodle::NoodleNode>, cmp_ln_Node, true>,
      std::__1::allocator<std::__1::__value_type<ln_Node, lab::noodle::NoodleNode> > >::__node_base_pointer' (aka 'std::__1::__tree_node_base<void *> *'), which are not related by inheritance, is not allowed
                  static_cast<__node_base_pointer>(__ptr));
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
7 warnings and 6 errors generated.
make[2]: *** [CMakeFiles/LabSoundGraphToy.dir/src/lab_noodle.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
1 error generated.
make[2]: *** [CMakeFiles/LabSoundGraphToy.dir/src/LabSoundInterface.cpp.o] Error 1
[ 98%] Building CXX object third/LabSound/CMakeFiles/LabSoundExample.dir/examples/src/ExamplesMain.cpp.o


```

**Comment by meshula** [comment]
Hmm, perhaps the push was incomplete. I'm double checking for a missed commit.

**Comment by meshula** [comment]
Again, thanks for the reports, hopefully this time is the charm.

I've pushed all the necessary fixes to this fork and the main repository.

This repo is a development fork - the main repo is here - https://github.com/LabSound/LabSoundGraphToy/

I fixed the missing includes you pointed out, the c++14 setting, the references to the submodules, and hopefully made the installation a bit simpler.

When you try again, be sure to build the Install target as well, so that the application's font is copied to the right place.
